#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — protection settings are preserved, but credentials must be re-entered.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

usage() {
  cat <<'EOF'
Usage: scripts/setup_release_signing_credentials.sh

Interactive macOS wizard for configuring the protected release-signing GitHub
environment used by Oscar-V4/apple-reminders. It validates one Developer ID
Application certificate, a matching exported .p12, and an App Store Connect
Team API .p8 key before uploading three environment secrets and three public
environment variables.

The wizard never writes credentials into the repository. It refuses to target
any repository other than Oscar-V4/apple-reminders and preserves every existing
reviewer, wait timer, and prevent-self-review setting.
EOF
}

case "${1:-}" in
  -h|--help)
    usage
    exit 0
    ;;
  "") ;;
  *)
    printf 'Unknown argument: %s\n' "$1" >&2
    usage >&2
    exit 2
    ;;
esac

# Never allow shell tracing or GitHub CLI debug logs to expose captured input.
set +x
unset GH_DEBUG

EXPECTED_REPO_SLUG="Oscar-V4/apple-reminders"
RELEASE_ENVIRONMENT="release-signing"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CREDENTIAL_TMP_DIR=""
P12_PATH=""
P8_PATH=""
WRITTEN_VARIABLE=()

die() {
  printf '\n  %s✗ %s%s\n\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 ||
    die "필수 명령어 '$1'을 찾지 못했습니다. 설치한 뒤 다시 실행하세요."
}

cleanup_temporary_credentials() {
  if [[ -n "${P12_PATH:-}" && -n "${CREDENTIAL_TMP_DIR:-}" && "$P12_PATH" == "$CREDENTIAL_TMP_DIR/developer-id-application.p12" ]]; then
    rm -f -- "$P12_PATH"
  fi
  if [[ -n "${CREDENTIAL_TMP_DIR:-}" && -d "$CREDENTIAL_TMP_DIR" ]]; then
    rmdir "$CREDENTIAL_TMP_DIR" >/dev/null 2>&1 || true
  fi
  unset P12_PASSWORD P12_PASSWORD_CONFIRM 2>/dev/null || true
}

normalize_path() {
  local value="$1"
  value="${value#\"}"; value="${value%\"}"
  value="${value#\'}"; value="${value%\'}"
  value="${value/#\~/$HOME}"
  value="${value//\\ / }"
  printf '%s' "$value"
}

verify_p12() {
  local path="$1" password="$2" cert_pem key_pem subject cert_hash key_hash

  openssl pkcs12 -in "$path" -noout -passin fd:3 3<<<"$password" >/dev/null 2>&1 || return 1
  cert_pem="$(openssl pkcs12 -in "$path" -clcerts -nokeys -passin fd:3 3<<<"$password" 2>/dev/null)" || return 1
  key_pem="$(openssl pkcs12 -in "$path" -nocerts -nodes -passin fd:3 3<<<"$password" 2>/dev/null)" || return 1
  [[ "$(printf '%s\n' "$cert_pem" | grep -c -- '-----BEGIN CERTIFICATE-----' || true)" == "1" ]] || return 1
  [[ "$(printf '%s\n' "$key_pem" | grep -c -- '-----BEGIN .*PRIVATE KEY-----' || true)" == "1" ]] || return 1

  subject="$(printf '%s\n' "$cert_pem" | openssl x509 -noout -subject 2>/dev/null)" || return 1
  [[ "$subject" == *"Developer ID Application"* ]] || return 1
  [[ "$subject" == *"$APPLE_TEAM_ID"* ]] || return 1

  cert_hash="$(
    printf '%s\n' "$cert_pem" |
      openssl x509 -pubkey -noout 2>/dev/null |
      openssl pkey -pubin -outform DER 2>/dev/null |
      openssl dgst -sha256 2>/dev/null
  )" || return 1
  key_hash="$(
    printf '%s\n' "$key_pem" |
      openssl pkey -pubout -outform DER 2>/dev/null |
      openssl dgst -sha256 2>/dev/null
  )" || return 1
  unset cert_pem key_pem
  [[ -n "$cert_hash" && "$cert_hash" == "$key_hash" ]]
}

set_environment_secret_value() {
  local name="$1" value="$2"
  if printf '%s' "$value" |
      gh secret set "$name" --env "$RELEASE_ENVIRONMENT" --repo "$REPO_SLUG" >/dev/null; then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ 등록%s %s (GitHub 환경 비밀)\n' "$GREEN" "$RESET" "$name"
  else
    die "GitHub 환경 비밀 $name 등록에 실패했습니다. 비밀값은 출력되지 않았습니다."
  fi
}

set_environment_secret_file_base64() {
  local name="$1" path="$2"
  if openssl base64 -A -in "$path" |
      gh secret set "$name" --env "$RELEASE_ENVIRONMENT" --repo "$REPO_SLUG" >/dev/null; then
    WRITTEN_SECRET+=("$name")
    printf '  %s✓ 등록%s %s (파일 내용을 Base64로 암호화 전송)\n' "$GREEN" "$RESET" "$name"
  else
    die "GitHub 환경 비밀 $name 등록에 실패했습니다. 비밀값은 출력되지 않았습니다."
  fi
}

set_environment_variable() {
  local name="$1" value="$2"
  if gh variable set "$name" --env "$RELEASE_ENVIRONMENT" --repo "$REPO_SLUG" --body "$value" >/dev/null; then
    WRITTEN_VARIABLE+=("$name")
    printf '  %s✓ 등록%s %s (GitHub 환경 변수)\n' "$GREEN" "$RESET" "$name"
  else
    die "GitHub 환경 변수 $name 등록에 실패했습니다."
  fi
}

contains_line() {
  local needle="$1" haystack="$2"
  printf '%s\n' "$haystack" | grep -Fqx "$needle"
}

ensure_release_environment() {
  local environments_json environment_count environment_json unknown_rule_count
  local reviewer_rule_count reviewer_count invalid_reviewer_count wait_rule_count
  local wait_timer prevent_self custom_branches protected_branches branch_json
  local invalid_branch_count main_branch_count

  environments_json="$(gh api "repos/$REPO_SLUG/environments?per_page=100")" ||
    die "GitHub 환경 목록을 읽지 못했습니다. 기존 보호 설정을 확인할 수 없어 중단합니다."
  [[ "$(jq -r '.total_count | type' <<<"$environments_json")" == "number" ]] ||
    die "GitHub 환경 목록 응답 형식을 확인하지 못했습니다."
  [[ "$(jq -r '.environments | length' <<<"$environments_json")" == "$(jq -r '.total_count' <<<"$environments_json")" ]] ||
    die "GitHub 환경 목록이 한 페이지를 넘어 기존 설정을 안전하게 판별할 수 없습니다."

  environment_count="$(
    jq --arg name "$RELEASE_ENVIRONMENT" '[.environments[] | select(.name == $name)] | length' \
      <<<"$environments_json"
  )"
  if [[ "$environment_count" == "0" ]]; then
    jq -n --argjson reviewer_id "$REVIEWER_ID" \
      '{wait_timer:0,prevent_self_review:false,reviewers:[{type:"User",id:$reviewer_id}],deployment_branch_policy:{protected_branches:false,custom_branch_policies:true}}' |
      gh api --method PUT "repos/$REPO_SLUG/environments/$RELEASE_ENVIRONMENT" --input - >/dev/null ||
      die "GitHub 환경 '$RELEASE_ENVIRONMENT'을 만들지 못했습니다."
  elif [[ "$environment_count" != "1" ]]; then
    die "동일한 이름의 GitHub 환경을 안전하게 식별하지 못했습니다."
  fi

  environment_json="$(gh api "repos/$REPO_SLUG/environments/$RELEASE_ENVIRONMENT")" ||
    die "GitHub 환경 보호 설정을 읽지 못했습니다. 비밀 등록 전에 중단합니다."
  [[ "$(jq -r '.name' <<<"$environment_json")" == "$RELEASE_ENVIRONMENT" ]] ||
    die "예상한 GitHub 환경을 읽지 못했습니다."

  unknown_rule_count="$(
    jq '[.protection_rules[]? | select(.type != "required_reviewers" and .type != "wait_timer" and .type != "branch_policy")] | length' \
      <<<"$environment_json"
  )"
  [[ "$unknown_rule_count" == "0" ]] ||
    die "알 수 없는 GitHub 환경 보호 규칙이 있어 기존 설정 보존을 보장할 수 없습니다."

  reviewer_rule_count="$(
    jq '[.protection_rules[]? | select(.type == "required_reviewers")] | length' \
      <<<"$environment_json"
  )"
  [[ "$reviewer_rule_count" == "1" ]] ||
    die "release-signing 환경에는 정확히 하나의 필수 승인자 규칙이 있어야 합니다. 기존 설정은 변경하지 않았습니다."
  reviewer_count="$(
    jq '[.protection_rules[] | select(.type == "required_reviewers") | .reviewers[]?] | length' \
      <<<"$environment_json"
  )"
  [[ "$reviewer_count" -ge 1 ]] ||
    die "release-signing 환경에 필수 승인자가 없습니다. 비밀 등록 전에 중단합니다."
  invalid_reviewer_count="$(
    jq '[.protection_rules[] | select(.type == "required_reviewers") | .reviewers[]? | select((.type != "User" and .type != "Team") or (.reviewer.id | type) != "number")] | length' \
      <<<"$environment_json"
  )"
  [[ "$invalid_reviewer_count" == "0" ]] ||
    die "기존 승인자 설정 형식을 안전하게 확인하지 못했습니다."
  prevent_self="$(
    jq -r '.protection_rules[] | select(.type == "required_reviewers") | .prevent_self_review | type' \
      <<<"$environment_json"
  )"
  [[ "$prevent_self" == "boolean" ]] ||
    die "기존 prevent-self-review 설정을 읽지 못했습니다."

  wait_rule_count="$(
    jq '[.protection_rules[]? | select(.type == "wait_timer")] | length' \
      <<<"$environment_json"
  )"
  [[ "$wait_rule_count" -le 1 ]] ||
    die "기존 wait timer 설정을 안전하게 확인하지 못했습니다."
  if [[ "$wait_rule_count" == "1" ]]; then
    wait_timer="$(
      jq -r '.protection_rules[] | select(.type == "wait_timer") | .wait_timer' \
        <<<"$environment_json"
    )"
    [[ "$wait_timer" =~ ^[0-9]+$ ]] ||
      die "기존 wait timer 값을 안전하게 확인하지 못했습니다."
  fi

  custom_branches="$(jq -r '.deployment_branch_policy.custom_branch_policies' <<<"$environment_json")"
  protected_branches="$(jq -r '.deployment_branch_policy.protected_branches' <<<"$environment_json")"
  [[ "$custom_branches" == "true" && "$protected_branches" == "false" ]] ||
    die "기존 배포 브랜치 정책을 덮어쓰지 않고 main-only로 만들 수 없어 중단합니다."

  branch_json="$(
    gh api "repos/$REPO_SLUG/environments/$RELEASE_ENVIRONMENT/deployment-branch-policies?per_page=100"
  )" || die "기존 배포 브랜치 정책을 읽지 못했습니다."
  [[ "$(jq -r '.branch_policies | length' <<<"$branch_json")" == "$(jq -r '.total_count' <<<"$branch_json")" ]] ||
    die "배포 브랜치 정책 목록이 한 페이지를 넘어 안전하게 확인할 수 없습니다."
  invalid_branch_count="$(
    jq --arg branch "$DEFAULT_BRANCH" '[.branch_policies[] | select(.name != $branch or .type != "branch")] | length' \
      <<<"$branch_json"
  )"
  [[ "$invalid_branch_count" == "0" ]] ||
    die "main 이외의 배포 브랜치 또는 태그 정책이 있습니다. 기존 정책은 변경하지 않았습니다."
  main_branch_count="$(
    jq --arg branch "$DEFAULT_BRANCH" '[.branch_policies[] | select(.name == $branch and .type == "branch")] | length' \
      <<<"$branch_json"
  )"
  if [[ "$main_branch_count" == "0" ]]; then
    gh api --method POST \
      "repos/$REPO_SLUG/environments/$RELEASE_ENVIRONMENT/deployment-branch-policies" \
      -f name="$DEFAULT_BRANCH" -f type=branch >/dev/null ||
      die "GitHub 환경의 기본 브랜치 제한을 만들지 못했습니다."
  elif [[ "$main_branch_count" != "1" ]]; then
    die "기본 브랜치 정책을 하나로 확정하지 못했습니다."
  fi

  branch_json="$(
    gh api "repos/$REPO_SLUG/environments/$RELEASE_ENVIRONMENT/deployment-branch-policies?per_page=100"
  )" || die "배포 브랜치 정책을 다시 확인하지 못했습니다."
  [[ "$(jq -r '.total_count' <<<"$branch_json")" == "1" ]] ||
    die "release-signing 환경이 main-only인지 확인하지 못했습니다."
  [[ "$(jq -r '.branch_policies[0].name' <<<"$branch_json")" == "$DEFAULT_BRANCH" ]] ||
    die "release-signing 환경의 유일한 브랜치가 main이 아닙니다."
}

trap cleanup_temporary_credentials EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

[[ -t 0 ]] || die "이 마법사는 사람의 입력이 필요한 대화형 터미널에서 실행해야 합니다."
[[ "$(uname -s)" == "Darwin" ]] || die "Developer ID 인증서 내보내기는 macOS에서 실행해야 합니다."

cd "$REPO_ROOT"
CREDENTIAL_TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/apple-reminders-release-signing.XXXXXX")"
chmod 700 "$CREDENTIAL_TMP_DIR"
P12_PATH="$CREDENTIAL_TMP_DIR/developer-id-application.p12"
# The wizard deliberately keeps captured credentials out of the repository's .env.
ENV_FILE="$CREDENTIAL_TMP_DIR/nonpersistent.env"

banner "Apple Reminders 릴리스 서명 설정"

stage "사전 점검"
say "현재 Mac의 Developer ID 인증서와 정확한 GitHub 대상 저장소를 확인합니다."
require_command security
require_command openssl
require_command gh
require_command jq
require_command uname

gh auth status >/dev/null 2>&1 || die "GitHub CLI 로그인이 필요합니다. 먼저 'gh auth login'을 실행하세요."
REPO_SLUG="$(gh repo view --json nameWithOwner --jq '.nameWithOwner' 2>/dev/null)"
[[ "$REPO_SLUG" == "$EXPECTED_REPO_SLUG" ]] ||
  die "대상 저장소가 $EXPECTED_REPO_SLUG가 아닙니다. 감지된 저장소: ${REPO_SLUG:-없음}"
[[ "$(gh api "repos/$EXPECTED_REPO_SLUG" --jq '.full_name' 2>/dev/null)" == "$EXPECTED_REPO_SLUG" ]] ||
  die "GitHub API에서 정확한 대상 저장소를 확인하지 못했습니다."

IDENTITY_OUTPUT="$(security find-identity -v -p codesigning 2>/dev/null)"
DEVELOPER_ID_COUNT="$(printf '%s\n' "$IDENTITY_OUTPUT" | grep -c '"Developer ID Application:' || true)"
[[ "$DEVELOPER_ID_COUNT" == "1" ]] ||
  die "유효한 Developer ID Application 인증서가 정확히 1개여야 합니다. 현재: $DEVELOPER_ID_COUNT개"
APPLE_TEAM_ID="$(printf '%s\n' "$IDENTITY_OUTPUT" | sed -n 's/.*Developer ID Application:.*(\([A-Z0-9][A-Z0-9]*\))".*/\1/p' | tail -n 1)"
[[ "$APPLE_TEAM_ID" =~ ^[A-Z0-9]{10}$ ]] ||
  die "Developer ID 인증서에서 10자리 Team ID를 읽지 못했습니다."
[[ "$APPLE_TEAM_ID" == "V8347N9346" ]] ||
  die "Developer ID 인증서가 이 저장소의 canonical publisher와 일치하지 않습니다. 기존 GitHub 자격 증명은 변경하지 않았습니다."

step "GitHub 대상 저장소: $REPO_SLUG"
step "유효한 Developer ID Application 인증서 1개를 확인했습니다."
step "GitHub 환경 '$RELEASE_ENVIRONMENT'에 비밀 3개와 공개 변수 3개를 등록합니다."
if ! confirm "이 저장소의 릴리스 서명 설정을 계속할까요?"; then
  die "사용자가 설정을 취소했습니다."
fi

stage "Developer ID를 임시 .p12로 내보내기"
say "Keychain Access에서 기존 Developer ID 인증서와 개인 키를 암호로 보호된 임시 파일로 내보냅니다."
if ! open -a "Keychain Access" >/dev/null 2>&1; then
  warn "Keychain Access를 자동으로 열지 못했습니다. 응용 프로그램 → 유틸리티에서 직접 여세요."
fi
step "왼쪽에서 'login' 키체인과 'My Certificates(내 인증서)'를 선택하세요."
step "'Developer ID Application' 인증서의 화살표를 펼쳐 개인 키가 함께 있는지 확인하세요."
step "인증서 행을 우클릭하고 'Export(내보내기)'를 선택하세요."
step "Shift+Command+G를 눌러 아래 임시 폴더로 이동한 뒤 파일명을 developer-id-application.p12로 저장하세요."
say "$CREDENTIAL_TMP_DIR"
step "내보내기 암호를 새로 정해 입력하고, 요청되면 Mac 로그인 암호로 승인하세요."
pause "Keychain Access에서 .p12 저장을 마쳤으면 Enter를 누르세요."

while [[ ! -f "$P12_PATH" ]]; do
  warn "예상한 위치에서 developer-id-application.p12를 찾지 못했습니다."
  step "저장 위치와 파일명을 다시 확인하세요: $P12_PATH"
  pause "저장을 마쳤으면 Enter를 누르세요. (중단: Ctrl-C)"
done
[[ ! -L "$P12_PATH" ]] || die ".p12 파일이 심볼릭 링크여서 안전하게 사용할 수 없습니다."
chmod 600 "$P12_PATH"

while true; do
  ask_secret P12_PASSWORD "Keychain Access에서 정한 .p12 내보내기 암호:"
  ask_secret P12_PASSWORD_CONFIRM "같은 암호를 한 번 더 입력:"
  if [[ -z "$P12_PASSWORD" ]]; then
    warn "빈 암호는 사용할 수 없습니다."
  elif [[ "$P12_PASSWORD" != "$P12_PASSWORD_CONFIRM" ]]; then
    warn "두 암호가 일치하지 않습니다. 다시 입력하세요."
  elif verify_p12 "$P12_PATH" "$P12_PASSWORD"; then
    break
  else
    warn ".p12 암호, Developer ID 인증서, 개인 키 조합을 검증하지 못했습니다. 다시 입력하거나 파일을 다시 내보내세요."
  fi
done
unset P12_PASSWORD_CONFIRM
printf '  %s✓ 확인%s Developer ID 인증서와 일치하는 개인 키가 .p12 안에 있습니다.\n' "$GREEN" "$RESET"

stage "App Store Connect Team API 키 확인"
say "이미 공증 전용 Team API 키와 보관한 .p8이 있다면 그대로 재사용합니다. 둘 중 하나가 없을 때만 새 키를 만듭니다."
warn "새 .p8 개인 키는 한 번만 다운로드할 수 있습니다. 새 키를 만들었다면 다운로드 창을 닫기 전에 안전하게 보관하세요."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "기존 공증 전용 키와 .p8을 보관 중이면 새 키를 만들지 말고 해당 Key ID와 파일을 준비하세요."
step "기존 키를 재사용할 수 없을 때만 Team Keys의 +를 누르고, 이름은 'Apple Reminders Release Notarization', 권한은 'Developer'로 생성하세요."
step "새 키를 만든 경우에만 Download API Key를 눌러 AuthKey_….p8을 한 번 다운로드하세요."
step "페이지의 Issuer ID와 사용할 키 행의 Key ID를 복사해 두세요. 둘은 비밀값이 아닙니다."
pause "기존 키 준비 또는 필요한 새 키 생성을 마쳤으면 Enter를 누르세요."

while true; do
  ask APPLE_NOTARY_KEY_ID "Key ID를 붙여넣으세요:"
  APPLE_NOTARY_KEY_ID="$(printf '%s' "$APPLE_NOTARY_KEY_ID" | tr -d '[:space:]')"
  [[ "$APPLE_NOTARY_KEY_ID" =~ ^[A-Z0-9]{10}$ ]] && break
  warn "Key ID 형식이 올바르지 않습니다. 영문 대문자와 숫자로 된 값을 다시 복사하세요."
done

while true; do
  ask APPLE_NOTARY_ISSUER_ID "Issuer ID를 붙여넣으세요:"
  APPLE_NOTARY_ISSUER_ID="$(printf '%s' "$APPLE_NOTARY_ISSUER_ID" | tr -d '[:space:]')"
  [[ "$APPLE_NOTARY_ISSUER_ID" =~ ^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$ ]] && break
  warn "Issuer ID는 하이픈이 포함된 UUID 형식이어야 합니다. 페이지에서 다시 복사하세요."
done

while true; do
  ask P8_PATH_INPUT "다운로드한 AuthKey_….p8의 전체 경로를 붙여넣으세요 (Finder에서 끌어와도 됩니다):"
  P8_PATH="$(normalize_path "$P8_PATH_INPUT")"
  if [[ ! -f "$P8_PATH" || -L "$P8_PATH" ]]; then
    warn "그 경로에서 안전한 일반 .p8 파일을 찾지 못했습니다."
  elif [[ "$(basename "$P8_PATH")" != *.p8 ]]; then
    warn "선택한 파일의 확장자가 .p8이 아닙니다."
  elif ! P8_PARENT="$(CDPATH= cd -- "$(dirname -- "$P8_PATH")" && pwd -P)"; then
    warn ".p8 파일의 실제 상위 폴더를 확인하지 못했습니다."
  elif P8_PATH="$P8_PARENT/$(basename -- "$P8_PATH")" && \
      [[ "$P8_PATH" == "$REPO_ROOT" || "$P8_PATH" == "$REPO_ROOT"/* ]]; then
    warn ".p8 개인 키는 Git 저장소 안에 둘 수 없습니다. 저장소 밖의 암호화 보관 위치로 먼저 옮기세요."
  elif ! openssl pkey -in "$P8_PATH" -check -noout >/dev/null 2>&1; then
    warn "선택한 파일을 유효한 개인 키로 확인하지 못했습니다."
  else
    break
  fi
done
if [[ "$(basename "$P8_PATH")" != "AuthKey_${APPLE_NOTARY_KEY_ID}.p8" ]]; then
  warn ".p8 파일명과 입력한 Key ID가 일치하지 않습니다. 파일을 이름 변경했다면 정상일 수 있습니다."
  if ! confirm "App Store Connect에서 같은 키를 선택한 것이 확실한가요?"; then
    die "Key ID와 .p8 파일을 다시 확인한 뒤 마법사를 재실행하세요."
  fi
fi
printf '  %s✓ 확인%s Team API 개인 키 파일 형식이 유효합니다.\n' "$GREEN" "$RESET"

stage "GitHub release-signing 환경 구성"
say "이제 외부 변경을 수행합니다. 기존 보호 규칙을 먼저 읽고 보존한 뒤 6개 값을 등록합니다."
step "공개 변수: APPLE_TEAM_ID, APPLE_NOTARY_KEY_ID, APPLE_NOTARY_ISSUER_ID"
step "비밀: APPLE_DEVELOPER_ID_P12_B64, APPLE_DEVELOPER_ID_P12_PASSWORD, APPLE_NOTARY_KEY_P8_B64"
note "비밀 파일 내용과 암호는 터미널에 출력하지 않습니다. gh가 로컬에서 암호화해 전송합니다."
if ! confirm "GitHub 저장소 $REPO_SLUG에 지금 등록할까요?"; then
  die "GitHub 설정 변경 전에 사용자가 취소했습니다."
fi

REVIEWER_ID="$(gh api user --jq '.id')"
DEFAULT_BRANCH="$(gh repo view "$REPO_SLUG" --json defaultBranchRef --jq '.defaultBranchRef.name')"
[[ "$REVIEWER_ID" =~ ^[0-9]+$ && "$DEFAULT_BRANCH" == "main" ]] ||
  die "GitHub 승인 사용자 또는 main 기본 브랜치를 확인하지 못했습니다."

ensure_release_environment
printf '  %s✓ 보존%s 기존 승인자·대기 시간·self-review 설정\n' "$GREEN" "$RESET"
printf '  %s✓ 보호%s 필수 승인과 main 브랜치 전용 정책\n' "$GREEN" "$RESET"

set_environment_variable APPLE_TEAM_ID "$APPLE_TEAM_ID"
set_environment_variable APPLE_NOTARY_KEY_ID "$APPLE_NOTARY_KEY_ID"
set_environment_variable APPLE_NOTARY_ISSUER_ID "$APPLE_NOTARY_ISSUER_ID"
set_environment_secret_file_base64 APPLE_DEVELOPER_ID_P12_B64 "$P12_PATH"
set_environment_secret_value APPLE_DEVELOPER_ID_P12_PASSWORD "$P12_PASSWORD"
set_environment_secret_file_base64 APPLE_NOTARY_KEY_P8_B64 "$P8_PATH"
unset P12_PASSWORD

stage "등록 확인 및 임시 파일 정리"
say "GitHub는 비밀값을 다시 보여주지 않으므로, 등록된 이름과 환경만 확인합니다."
REGISTERED_SECRETS="$(gh secret list --env "$RELEASE_ENVIRONMENT" --repo "$REPO_SLUG" --json name --jq '.[].name')"
REGISTERED_VARIABLES="$(gh variable list --env "$RELEASE_ENVIRONMENT" --repo "$REPO_SLUG" --json name --jq '.[].name')"

for name in APPLE_DEVELOPER_ID_P12_B64 APPLE_DEVELOPER_ID_P12_PASSWORD APPLE_NOTARY_KEY_P8_B64; do
  contains_line "$name" "$REGISTERED_SECRETS" ||
    die "GitHub 환경에서 비밀 $name을 확인하지 못했습니다."
done
for name in APPLE_TEAM_ID APPLE_NOTARY_KEY_ID APPLE_NOTARY_ISSUER_ID; do
  contains_line "$name" "$REGISTERED_VARIABLES" ||
    die "GitHub 환경에서 변수 $name을 확인하지 못했습니다."
done
printf '  %s✓ 확인%s 비밀 3개와 공개 변수 3개의 이름이 모두 등록됐습니다.\n' "$GREEN" "$RESET"

rm -f -- "$P12_PATH"
rmdir "$CREDENTIAL_TMP_DIR" >/dev/null 2>&1 || true
P12_PATH=""
CREDENTIAL_TMP_DIR=""
printf '  %s✓ 정리%s 암호로 보호된 임시 .p12 작업 복사본을 삭제했습니다.\n' "$GREEN" "$RESET"
warn "다운로드한 .p8 원본은 삭제하지 않았습니다. 안전한 암호화 보관소로 옮기고 Git이나 채팅에 올리지 마세요."
note "등록된 값은 '$RELEASE_ENVIRONMENT' 환경을 사용하는 GitHub Actions 작업에서만 사용할 수 있습니다."
note "GitHub 변수 ${#WRITTEN_VARIABLE[@]}개: ${WRITTEN_VARIABLE[*]}"
pause "확인했으면 Enter를 눌러 마칩니다."

finish
